name: C/C++ CI

on:
  push:
    branches: [ "main", "add_tests" ]
  pull_request:
    branches: [ "main", "add_tests" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
