name: test_for_codecov

on:
  push:
    branches: 
      - main 
      - add_tests
  pull_request:
    branches: 
      - main 
      - add_tests

jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Before Install
        run: |
          sudo apt-get install g++
      - name: Compile program
        run: g++ -std=c++17 -o TestProgram -fprofile-arcs -ftest-coverage -fprofile-generate test/main_test.cpp
      - name: Run tests
        run: ./TestProgram
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          gcov_ignore: test/catch.h
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: thijsjanzen/seals
