name: test

on:
  push:
    branches: [ main, add_tests ]
  pull_request:
    branches: [ main, add_tests ]

jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Run Tests
        run: |
          g++ -o TestProgram -fprofile-arcs -ftest-coverage -fprofile-generate test/main.cpp
          ./TestProgram
          gcov -o . test/main.cpp
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: simulation.h.gcov,rand_t.h.gcov,parameters.h.gcov,individual.h.gcov,config_parser.h.gcov
